// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"example.com/m/v2/internal/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContextualLinkRepositoryInterface creates a new instance of MockContextualLinkRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextualLinkRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextualLinkRepositoryInterface {
	mock := &MockContextualLinkRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContextualLinkRepositoryInterface is an autogenerated mock type for the ContextualLinkRepositoryInterface type
type MockContextualLinkRepositoryInterface struct {
	mock.Mock
}

type MockContextualLinkRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextualLinkRepositoryInterface) EXPECT() *MockContextualLinkRepositoryInterface_Expecter {
	return &MockContextualLinkRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockContextualLinkRepositoryInterface
func (_mock *MockContextualLinkRepositoryInterface) Create(link string, contextualizedLink string) error {
	ret := _mock.Called(link, contextualizedLink)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(link, contextualizedLink)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextualLinkRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockContextualLinkRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - link string
//   - contextualizedLink string
func (_e *MockContextualLinkRepositoryInterface_Expecter) Create(link interface{}, contextualizedLink interface{}) *MockContextualLinkRepositoryInterface_Create_Call {
	return &MockContextualLinkRepositoryInterface_Create_Call{Call: _e.mock.On("Create", link, contextualizedLink)}
}

func (_c *MockContextualLinkRepositoryInterface_Create_Call) Run(run func(link string, contextualizedLink string)) *MockContextualLinkRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_Create_Call) Return(err error) *MockContextualLinkRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_Create_Call) RunAndReturn(run func(link string, contextualizedLink string) error) *MockContextualLinkRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByContextualizedLink provides a mock function for the type MockContextualLinkRepositoryInterface
func (_mock *MockContextualLinkRepositoryInterface) FindByContextualizedLink(contextualizedLink string) (*repositories.ContextualLink, error) {
	ret := _mock.Called(contextualizedLink)

	if len(ret) == 0 {
		panic("no return value specified for FindByContextualizedLink")
	}

	var r0 *repositories.ContextualLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*repositories.ContextualLink, error)); ok {
		return returnFunc(contextualizedLink)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *repositories.ContextualLink); ok {
		r0 = returnFunc(contextualizedLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.ContextualLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(contextualizedLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByContextualizedLink'
type MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call struct {
	*mock.Call
}

// FindByContextualizedLink is a helper method to define mock.On call
//   - contextualizedLink string
func (_e *MockContextualLinkRepositoryInterface_Expecter) FindByContextualizedLink(contextualizedLink interface{}) *MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call {
	return &MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call{Call: _e.mock.On("FindByContextualizedLink", contextualizedLink)}
}

func (_c *MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call) Run(run func(contextualizedLink string)) *MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call) Return(contextualLink *repositories.ContextualLink, err error) *MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call {
	_c.Call.Return(contextualLink, err)
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call) RunAndReturn(run func(contextualizedLink string) (*repositories.ContextualLink, error)) *MockContextualLinkRepositoryInterface_FindByContextualizedLink_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLink provides a mock function for the type MockContextualLinkRepositoryInterface
func (_mock *MockContextualLinkRepositoryInterface) FindByLink(link string) (*repositories.ContextualLink, error) {
	ret := _mock.Called(link)

	if len(ret) == 0 {
		panic("no return value specified for FindByLink")
	}

	var r0 *repositories.ContextualLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*repositories.ContextualLink, error)); ok {
		return returnFunc(link)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *repositories.ContextualLink); ok {
		r0 = returnFunc(link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.ContextualLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(link)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextualLinkRepositoryInterface_FindByLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLink'
type MockContextualLinkRepositoryInterface_FindByLink_Call struct {
	*mock.Call
}

// FindByLink is a helper method to define mock.On call
//   - link string
func (_e *MockContextualLinkRepositoryInterface_Expecter) FindByLink(link interface{}) *MockContextualLinkRepositoryInterface_FindByLink_Call {
	return &MockContextualLinkRepositoryInterface_FindByLink_Call{Call: _e.mock.On("FindByLink", link)}
}

func (_c *MockContextualLinkRepositoryInterface_FindByLink_Call) Run(run func(link string)) *MockContextualLinkRepositoryInterface_FindByLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_FindByLink_Call) Return(contextualLink *repositories.ContextualLink, err error) *MockContextualLinkRepositoryInterface_FindByLink_Call {
	_c.Call.Return(contextualLink, err)
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_FindByLink_Call) RunAndReturn(run func(link string) (*repositories.ContextualLink, error)) *MockContextualLinkRepositoryInterface_FindByLink_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockContextualLinkRepositoryInterface
func (_mock *MockContextualLinkRepositoryInterface) Upsert(link string, contextualizedLink string) error {
	ret := _mock.Called(link, contextualizedLink)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(link, contextualizedLink)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextualLinkRepositoryInterface_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockContextualLinkRepositoryInterface_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - link string
//   - contextualizedLink string
func (_e *MockContextualLinkRepositoryInterface_Expecter) Upsert(link interface{}, contextualizedLink interface{}) *MockContextualLinkRepositoryInterface_Upsert_Call {
	return &MockContextualLinkRepositoryInterface_Upsert_Call{Call: _e.mock.On("Upsert", link, contextualizedLink)}
}

func (_c *MockContextualLinkRepositoryInterface_Upsert_Call) Run(run func(link string, contextualizedLink string)) *MockContextualLinkRepositoryInterface_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_Upsert_Call) Return(err error) *MockContextualLinkRepositoryInterface_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextualLinkRepositoryInterface_Upsert_Call) RunAndReturn(run func(link string, contextualizedLink string) error) *MockContextualLinkRepositoryInterface_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
