// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDifyServiceInterface creates a new instance of MockDifyServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDifyServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDifyServiceInterface {
	mock := &MockDifyServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDifyServiceInterface is an autogenerated mock type for the DifyServiceInterface type
type MockDifyServiceInterface struct {
	mock.Mock
}

type MockDifyServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDifyServiceInterface) EXPECT() *MockDifyServiceInterface_Expecter {
	return &MockDifyServiceInterface_Expecter{mock: &_m.Mock}
}

// GetContextualLink provides a mock function for the type MockDifyServiceInterface
func (_mock *MockDifyServiceInterface) GetContextualLink(url string) (string, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GetContextualLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDifyServiceInterface_GetContextualLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContextualLink'
type MockDifyServiceInterface_GetContextualLink_Call struct {
	*mock.Call
}

// GetContextualLink is a helper method to define mock.On call
//   - url string
func (_e *MockDifyServiceInterface_Expecter) GetContextualLink(url interface{}) *MockDifyServiceInterface_GetContextualLink_Call {
	return &MockDifyServiceInterface_GetContextualLink_Call{Call: _e.mock.On("GetContextualLink", url)}
}

func (_c *MockDifyServiceInterface_GetContextualLink_Call) Run(run func(url string)) *MockDifyServiceInterface_GetContextualLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDifyServiceInterface_GetContextualLink_Call) Return(s string, err error) *MockDifyServiceInterface_GetContextualLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDifyServiceInterface_GetContextualLink_Call) RunAndReturn(run func(url string) (string, error)) *MockDifyServiceInterface_GetContextualLink_Call {
	_c.Call.Return(run)
	return _c
}
